# Learning Numpy and Pandas for Data Analysis

## Numpy - Numerical Python 
      - structure - Numpy ndimensional 
      - Super fast processing
      - it deals only in numeric values

### Creating a numpy Array 

Dimensional Array

In [4]:
import numpy as np

In [9]:
# using python list
lst = [1,2,3,4,5,6,7,8,9,10]
print(type(lst))
print(lst)

arr1d = np.array(lst)
print(type(arr1d))
print(arr1d)

<class 'list'>
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
<class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [11]:
lst * 2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Vectorized Operation
 

In [10]:
arr1d * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [12]:
arr1d/10

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [14]:
arr1d +2 

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [15]:
arr1d - 2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [16]:
arr1d % 2

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [18]:
arr1d.size

10

In [19]:
arr1d.ndim

1

In [22]:
arr1d.shape

(10,)

In [23]:
#Using numpy arange
arr1d = np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
#2dArray from python list
lst2d = [[1,2,3],[11,22,33],[111,222,333]]
lst2d

[[1, 2, 3], [11, 22, 33], [111, 222, 333]]

In [14]:
#2dArray from python list
la = [[1,2,3],[11,22,33],[111,222],"a"]
print(la)

[[1, 2, 3], [11, 22, 33], [111, 222], 'a']


In [13]:
ara = np.array(la)
ara

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [17]:
arr2d = np.array(lst2d)
print(arr2d)

[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]


In [26]:
arr2d.ndim

2

In [27]:
arr2d.shape

(3, 3)

In [19]:
arr2d = np.arange(36).reshape(6,6)
arr2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [22]:
arr2d = np.arange(36).reshape(2,18)
print(arr2d)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35]]


In [24]:
arr2d = np.arange(36).reshape(9,4)
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [25]:
arr1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
arr1d[7]

8

In [27]:
arr1d[4:8]

array([5, 6, 7, 8])

In [28]:
arr1d[-1]

10

In [29]:
arr1d[5]

6

In [30]:
arr1d[5:6]

array([6])

In [31]:
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [32]:
arr2d.reshape(4,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [33]:
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [34]:
arr2d = arr2d.reshape(4,9)

In [35]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [56]:
arr2d[::2,::2]

array([[ 0,  2,  4,  6,  8],
       [18, 20, 22, 24, 26]])

In [45]:
# index value 23 from arr2d
arr2d[-1][-1]

35

In [37]:
arr2d[2,5]

23

In [38]:
# arr2d[row,col]  >>> [startrow:endrow,statcol:endcol]

arr2d[1:2,2:7]
#Slice

array([[11, 12, 13, 14, 15]])

In [39]:
arr2d[1:3,5:7]

array([[14, 15],
       [23, 24]])

In [40]:
arr2d[0:4, 6:9]

array([[ 6,  7,  8],
       [15, 16, 17],
       [24, 25, 26],
       [33, 34, 35]])

In [41]:
arr2d[:, 6:]

array([[ 6,  7,  8],
       [15, 16, 17],
       [24, 25, 26],
       [33, 34, 35]])

In [42]:
arr2d[2,4:7]


array([22, 23, 24])

In [43]:
arr2d[:,-1]

array([ 8, 17, 26, 35])

In [59]:
arr2d[:,8:]

array([[ 8],
       [17],
       [26],
       [35]])

In [79]:
arr2d[:,::3]

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24],
       [27, 30, 33]])

In [80]:
arr2d[:,::-2]

array([[ 8,  6,  4,  2,  0],
       [17, 15, 13, 11,  9],
       [26, 24, 22, 20, 18],
       [35, 33, 31, 29, 27]])

In [60]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
type(np.arange(10))

numpy.ndarray

In [62]:
np.arange(10).ndim

1

In [63]:
np.arange(10).shape

(10,)

In [64]:
np.arange(10).reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [65]:
type(np.arange(10).reshape(1,10))

numpy.ndarray

In [66]:
np.arange(10).reshape(1,10).ndim

2

In [67]:
np.arange(10).reshape(1,10).shape

(1, 10)

In [75]:
np.array([[19]])

array([[19]])

In [74]:
np.array([[19,1, 2], [4, 5, 6]])

array([[19,  1,  2],
       [ 4,  5,  6]])

In [76]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [78]:
# Fancy Indexing
arr2d[[0,2],[2,7]]


array([ 2, 25])

In [81]:
arr3d = np.arange(64).reshape(4,4,4)

In [82]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [83]:
arr3d[1][2][2]

26

In [84]:
arr3d[3][1][3]

55

In [111]:
arr3d[2:3, :3, :3]

array([[[32, 33, 34],
        [36, 37, 38],
        [40, 41, 42]]])

In [114]:
arr3d[2:3, :3, :3].shape

(1, 3, 3)

In [112]:
arr3d[2:3, :3, 0]

array([[32, 36, 40]])

In [113]:
arr3d[2:3, :3, 0].shape

(1, 3)

In [115]:
arr3d[3:4,1:3,1:3]

array([[[53, 54],
        [57, 58]]])

In [116]:
arr3d[:,2:3,1:3]

array([[[ 9, 10]],

       [[25, 26]],

       [[41, 42]],

       [[57, 58]]])

In [117]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [121]:
type(np.zeros(12))

numpy.ndarray

In [120]:
type(np.zeros(12)[0])

numpy.float64

In [118]:
np.zeros((4,5),dtype='int')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [122]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [123]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [124]:
np.ones((5,5))*10

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [125]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [152]:
arr2d1 = np.arange(12).reshape(3,4)
arr2d1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [153]:
arr2d1 = np.arange(12,24).reshape(3,4)

In [154]:
arr2d1

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [155]:
arr2d2 = np.random.randn(3,4)

In [156]:
arr2d2

array([[-0.11555903, -1.93154901, -0.23451549,  0.91152078],
       [ 0.11439848, -1.66295218,  1.04374763,  0.83000642],
       [ 0.89121313,  1.05600579, -1.85154622, -0.0583019 ]])

In [157]:
arr2d1 + arr2d2

array([[11.88444097, 11.06845099, 13.76548451, 15.91152078],
       [16.11439848, 15.33704782, 19.04374763, 19.83000642],
       [20.89121313, 22.05600579, 20.14845378, 22.9416981 ]])